import type { Metadata } from "next";
import {  Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import Header from "@/components/Header";
import NavSideDesktop from "@/components/NavSideDesktop";
const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable}  antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
       
          <Header />
          <NavSideDesktop />
          <main className="lg:ml-64 mt-[68px]">
              {children}
          </main>

         
          </ThemeProvider>
      </body>
    </html>
  );
}
