version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - docker.env
    depends_on:
      - postgres
      - redis
    networks:
      - nestjs-app-network

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    env_file:
      - docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nestjs-app-network
 
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
        - redis
    networks:
      - nestjs-app-network


volumes:
  postgres_data:
  redis_data:
networks:
  nestjs-app-network:
    driver: bridge

